# Generated by Django 5.2.11 on 2026-07-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('numero_oc', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Número OC')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('fecha_oc', models.DateField(blank=True, null=True, verbose_name='Fecha OC')),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proyecto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total SIN IVA')),
                ('tiempo_fabricacion', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de fabricación (días)')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha Compromiso')),
                ('estado', models.CharField(default='En proceso', max_length=100, verbose_name='Estado')),
                ('porcentaje_entregado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Entregado')),
                ('fecha_ultima_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Última Entrega')),
                ('dias_restantes', models.IntegerField(blank=True, null=True, verbose_name='Días Restantes')),
                ('prioridad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prioridad')),
                ('guia_despacho_resumen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guía de Despacho (Resumen)')),
                ('factura_resumen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Factura (Resumen)')),
                ('fecha_factura', models.DateField(blank=True, null=True, verbose_name='Fecha Factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('oc_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link OC')),
                ('fmr_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link FMR')),
                ('plano_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link PLANO')),
                ('excel_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link EXCEL')),
                ('dossier_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link DOSSIER')),
                ('cotizacion_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link COTIZACIÓN')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_oc'],
            },
        ),
        migrations.CreateModel(
            name='FMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmr_code', models.CharField(max_length=100, unique=True, verbose_name='FMR Código')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha FMR')),
                ('cotizacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cotización N°')),
                ('guia_despacho', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guía Despacho')),
                ('factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura')),
                ('registro_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Registro Final (PDF)')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmrs', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'FMR',
                'verbose_name_plural': 'FMRs',
                'ordering': ['-fmr_code'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('guia_despacho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guía de Despacho')),
                ('cantidad_entregada', models.TextField(blank=True, null=True, verbose_name='Cantidad Entregada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Entrega')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Entrega Parcial',
                'verbose_name_plural': 'Entregas Parciales',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Materiales', 'Materiales'), ('Mano de Obra', 'Mano de Obra'), ('Subcontratos', 'Subcontratos'), ('Transporte', 'Transporte'), ('Otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción/Detalle')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto ($)')),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor/Empleado')),
                ('fecha', models.DateField(verbose_name='Fecha de Gasto')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Referencia (Boleta/Factura)')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Registro de Costo',
                'verbose_name_plural': 'Registros de Costos',
                'ordering': ['-fecha'],
            },
        ),
    ]
