# Generated by Django 5.2.11 on 2026-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción / Detalle'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Referencia'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del Gasto'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor / Empleado'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cantidad_entregada',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle / Cantidad Entregada'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('COMPLETA', 'Entrega Completa'), ('INCOMPLETA', 'Entrega Incompleta'), ('FACTURADO', 'Facturado')], default='COMPLETA', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='guia_despacho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Guía de Despacho'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='cotizacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Cotización'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Factura'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='fmr_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código FMR'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='cotizacion_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Cotización'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='dossier_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Dossier Calidad'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Facturado', 'Facturado'), ('Cerrado', 'Cerrado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='excel_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Excel'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='factura_resumen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fmr_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link FMR (PDF)'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='guia_despacho_resumen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guía de Despacho'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='oc_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link OC (PDF)'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='plano_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Planos'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='tiempo_fabricacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo fabricación (días háb.)'),
        ),
    ]
