# Generated by Django 6.0.2 on 2026-07-05 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordencompra_actualizado_en_ordencompra_creado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='guia_file',
            field=models.FileField(blank=True, null=True, upload_to='entregas/guias/', verbose_name='Archivo Guía de Despacho'),
        ),
        migrations.AddField(
            model_name='fmr',
            name='registro_file',
            field=models.FileField(blank=True, null=True, upload_to='fmr/registros/', verbose_name='Archivo Registro Final (PDF)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='cotizacion_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/cotizaciones/', verbose_name='Archivo Cotización'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='dossier_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/dossiers/', verbose_name='Archivo Dossier'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/excel/', verbose_name='Archivo Excel'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fmr_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/fmr/', verbose_name='Archivo FMR (PDF)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='oc_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/oc/', verbose_name='Archivo OC (PDF)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='plano_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/planos/', verbose_name='Archivo Planos'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('URGENTE', '🔴 Urgente'), ('ALTA', '🟠 Alta'), ('NORMAL', '🟡 Normal'), ('BAJA', '🟢 Baja')], max_length=100, null=True, verbose_name='Prioridad'),
        ),
        migrations.CreateModel(
            name='ItemOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=50, verbose_name='Línea / Item')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Item (Size/Code)')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unidad', models.CharField(default='EA', max_length=20, verbose_name='Unidad de Medida (UOM)')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='Cantidad')),
                ('peso_unitario_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Unitario (kg)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Precio Unitario')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cantidad Entregada')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Orden de Compra',
                'ordering': ['linea'],
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalles de la Acción')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidades', to='core.ordencompra', verbose_name='Orden de Compra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Trazabilidad',
                'verbose_name_plural': 'Registros de Trazabilidad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
