# Generated by Django 6.0.2 on 2026-07-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entrega_guia_file_fmr_registro_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='Cantidad Despachada')),
                ('numero_bulto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pallet / Bulto N°')),
                ('largo_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largo (mt)')),
                ('ancho_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho (mt)')),
                ('alto_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alto (mt)')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso (kg)')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list_items', to='core.entrega', verbose_name='Entrega / Despacho')),
                ('item_oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='core.itemoc', verbose_name='Ítem de la OC')),
            ],
            options={
                'verbose_name': 'Ítem de Packing List',
                'verbose_name_plural': 'Ítems de Packing List',
            },
        ),
    ]
