# Generated by Django 6.0.2 on 2026-07-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_packinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, verbose_name='N° Factura')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto ($)')),
                ('estado', models.CharField(choices=[('pendiente', '🟡 Pendiente de pago'), ('pagada', '🟢 Pagada')], default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('url_externa', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link externo (Drive/SharePoint)')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='Archivo Factura (PDF)')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.entrega', verbose_name='Entrega / Despacho asociado')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
