# Generated by Django 6.0.2 on 2026-07-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_factura_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Ayudante', 'Ayudante'), ('Ayudante mayor', 'Ayudante mayor'), ('Maestro', 'Maestro'), ('Maestro mayor', 'Maestro mayor'), ('Pintor', 'Pintor'), ('Adquisiciones', 'Adquisiciones'), ('Jefe Operaciones', 'Jefe de Operaciones'), ('Gerente', 'Gerente'), ('Otro', 'Otro (especificar)')], max_length=100, verbose_name='Cargo / Rol')),
                ('cargo_otro', models.CharField(blank=True, max_length=100, null=True, verbose_name="Especificar cargo (si 'Otro')")),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por hora ($)')),
                ('horas_normales', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Horas normales')),
                ('horas_extra', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Horas extra')),
                ('cantidad_trabajadores', models.IntegerField(default=1, verbose_name='Cantidad de trabajadores')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_mano_obra', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Costo de Mano de Obra',
                'verbose_name_plural': 'Costos de Mano de Obra',
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='CostoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255, verbose_name='Producto / Material')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Unitario ($)')),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_materiales', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Material Comprado',
                'verbose_name_plural': 'Materiales Comprados',
                'ordering': ['producto'],
            },
        ),
    ]
