# Generated by Django 6.0.2 on 2026-07-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_costos_detallados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Cargo')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio por Hora ($)')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='estado_facturacion',
            field=models.CharField(choices=[('facturado', 'Facturado'), ('por_facturar', 'Por facturar')], default='por_facturar', max_length=50, verbose_name='Estado de Facturación'),
        ),
        migrations.AddField(
            model_name='itemoc',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='itemoc',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='itemoc',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='itemoc',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio Total'),
        ),
        migrations.AddField(
            model_name='itemoc',
            name='size_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size Code'),
        ),
        migrations.AddField(
            model_name='itemoc',
            name='uom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UOM'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='alto_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alto Item'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='diametro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diámetro / Ø'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='estado_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Item'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='modelo_soporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo Soporte'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='unidades',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidades'),
        ),
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField(verbose_name='Días')),
                ('horas', models.IntegerField(verbose_name='Horas')),
                ('cantidad_trabajadores', models.IntegerField(verbose_name='Cantidad de Trabajadores')),
                ('horas_extra', models.IntegerField(default=0, verbose_name='Horas Extra')),
                ('costo_por_trabajador', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo por Trabajador')),
                ('mano_obra_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mano de Obra Base')),
                ('costo_horas_extra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Horas Extra')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total ($)')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manos_de_obra', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Mano de Obra (Detallada)',
                'verbose_name_plural': 'Mano de Obra (Detallada)',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255, verbose_name='Producto / Detalle')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitario ($)')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total ($)')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Materia Prima (Detallada)',
                'verbose_name_plural': 'Materias Primas (Detalladas)',
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_correlativo', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número Correlativo')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de Orden')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de Envío')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('empresa', models.CharField(default='MAESTRANZA BARK SPA', max_length=255, verbose_name='Empresa')),
                ('direccion', models.CharField(default='Camino F-30-E N° 1200, Quintero, Valparaíso', max_length=255, verbose_name='Dirección')),
                ('correo', models.CharField(default='contacto@maestranzabark.cl', max_length=255, verbose_name='Correo')),
                ('telefono', models.CharField(default='+56 9 1234 5678', max_length=255, verbose_name='Teléfono')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_lists', to='core.entrega', verbose_name='Despacho / Entrega')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Packing List',
                'verbose_name_plural': 'Packing Lists',
                'ordering': ['-numero_correlativo'],
            },
        ),
    ]
