# Generated by hand for preloading Cargo entries

from django.db import migrations

def preload_cargos(apps, schema_editor):
    Cargo = apps.get_model('core', 'Cargo')
    cargos_data = [
        {"nombre": "Ayudante", "precio_hora": 3000},
        {"nombre": "Adquisiciones", "precio_hora": 3000},
        {"nombre": "Maestro", "precio_hora": 4000},
        {"nombre": "Pintor", "precio_hora": 4000},
        {"nombre": "Maestro Mayor", "precio_hora": 4500},
        {"nombre": "Ayudante Mayor", "precio_hora": 4000},
        {"nombre": "Jefe Operaciones", "precio_hora": 4500},
        {"nombre": "Gerente", "precio_hora": 5000},
        {"nombre": "Administración", "precio_hora": 2500},
    ]
    for c in cargos_data:
        Cargo.objects.get_or_create(nombre=c["nombre"], defaults={"precio_hora": c["precio_hora"]})

def reverse_cargos(apps, schema_editor):
    Cargo = apps.get_model('core', 'Cargo')
    Cargo.objects.filter(
        nombre__in=[
            "Ayudante", "Adquisiciones", "Maestro", "Pintor", 
            "Maestro Mayor", "Ayudante Mayor", "Jefe Operaciones", 
            "Gerente", "Administración"
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cargo_entrega_estado_facturacion_and_more'),
    ]

    operations = [
        migrations.RunPython(preload_cargos, reverse_cargos),
    ]
