# Generated by Django 6.0.2 on 2026-07-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_preload_cargo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='tipo_medida',
            field=models.CharField(choices=[('diametro_alto', 'Ø / Alto'), ('largo_alto', 'L / H')], default='diametro_alto', max_length=20, verbose_name='Formato de Columnas'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='medida_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Medida 1 (Ø o L)'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='medida_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Medida 2 (Alto o H)'),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.IntegerField(blank=True, null=True, unique=True, verbose_name='N° Cotización')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valido_hasta', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('cliente_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente ID')),
                ('contacto_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Contacto')),
                ('contacto_cargo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo Contacto')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('giro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giro')),
                ('rut_receptor', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT')),
                ('direccion_receptor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('ciudad_receptor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Notas')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-numero_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=50, unique=True, verbose_name='N° Guía de Despacho')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('receptor_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social Receptor')),
                ('receptor_rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Receptor')),
                ('receptor_giro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giro Receptor')),
                ('receptor_direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Receptor')),
                ('receptor_comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna Receptor')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto / Persona que Recibe')),
                ('tipo_despacho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Despacho')),
                ('tipo_traslado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Traslado')),
                ('chofer_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Chofer')),
                ('chofer_rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Chofer')),
                ('patente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Patente')),
                ('transportista_rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Transportista')),
                ('direccion_destino', models.CharField(blank=True, max_length=400, null=True, verbose_name='Dirección de Destino')),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guia_despacho_obj', to='core.entrega', verbose_name='Entrega / Despacho')),
            ],
            options={
                'verbose_name': 'Guía de Despacho',
                'verbose_name_plural': 'Guías de Despacho',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación / Detalle')),
                ('valor_kg', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor por kg ($)')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('kg_por_unidad', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='kg por Unidad')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
            },
        ),
        migrations.CreateModel(
            name='ItemGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cantidad_unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cantidad / Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio Unitario ($)')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_guia', to='core.guiadespacho', verbose_name='Guía de Despacho')),
            ],
            options={
                'verbose_name': 'Ítem de Guía',
                'verbose_name_plural': 'Ítems de Guía',
            },
        ),
    ]
