# Generated by Django 6.0.2 on 2026-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_packing_medidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='peso_total_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Total OC (Respaldo/Opcional)'),
        ),
    ]
