# Generated by Django 6.0.2 on 2026-07-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ordencompra_peso_total_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazabilidades', to='core.ordencompra', verbose_name='Orden de Compra'),
        ),
    ]
