# Generated by Django 6.0.2 on 2026-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_trazabilidad_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='correo',
            field=models.CharField(default='administracion@maestranzabark.cl', max_length=255, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='direccion',
            field=models.CharField(default='Agustinas 1442', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='telefono',
            field=models.CharField(default='+56 9 4016 0112', max_length=255, verbose_name='Teléfono'),
        ),
    ]
