# Generated by Django 6.0.2 on 2026-07-27 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_packinglist_correo_alter_packinglist_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correos_notificacion_oc', models.TextField(default='kevin.angel@maestranzabark.cl', help_text='Ingresa uno o más correos separados por coma o por línea. Estos recibirán alertas cuando llegue una nueva OC.', verbose_name='Correos para Notificación de OCs')),
                ('correo_remitente_display', models.CharField(default='Maestranza Bark SPA', help_text='Nombre que aparecerá como remitente en los correos automáticos.', max_length=255, verbose_name='Nombre del Remitente en Emails')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='PerfilClienteExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT de la empresa en formato XX.XXX.XXX-X. Validado con algoritmo Módulo 11.', max_length=20, unique=True, verbose_name='RUT (Empresa)')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social / Empresa')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de Contacto')),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', '🟡 Pendiente de Aprobación'), ('aprobado', '🟢 Aprobado'), ('rechazado', '🔴 Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Aprobación')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Decisión')),
                ('observaciones_rechazo', models.TextField(blank=True, help_text='Si se rechaza el acceso, indica aquí el motivo para notificar al cliente.', null=True, verbose_name='Motivo de Rechazo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente_externo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente Externo',
                'verbose_name_plural': 'Perfiles de Clientes Externos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oc', models.CharField(help_text='Número de OC tal como aparece en el documento del cliente.', max_length=255, unique=True, verbose_name='N° de Orden de Compra')),
                ('archivo_oc', models.FileField(help_text='Sube el archivo PDF de tu Orden de Compra.', upload_to='oc_clientes/', verbose_name='Archivo PDF de la OC')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones del Cliente')),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Total (con IVA)')),
                ('estado', models.CharField(choices=[('borrador', '⬜ Borrador'), ('pendiente', '🟡 Pendiente de Revisión'), ('aceptada', '🟢 Aceptada'), ('rechazada', '🔴 Rechazada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones_bark', models.TextField(blank=True, help_text='Notas internas o motivo de rechazo. Se envía al cliente si se rechaza.', null=True, verbose_name='Observaciones de Bark')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Decisión')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocs_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='core.perfilclienteexterno', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'OC de Cliente Externo',
                'verbose_name_plural': 'OCs de Clientes Externos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
