# Generated by Django 6.0.2 on 2026-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_portal_oc_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='factura_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/facturas/', verbose_name='Archivo Factura (PDF)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='factura_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Factura (PDF)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='guia_file',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/guias/', verbose_name='Archivo Guía de Despacho (PDF)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='guia_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Guía de Despacho (PDF)'),
        ),
    ]
