# Generated by Django 6.0.2 on 2026-07-10 00:44

import datetime
import django.core.validators
import django.db.models.deletion
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 10.69 para indicar 10.69% (verificar antes de usar en producción)', max_digits=5)),
                ('vigente_desde', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
            },
        ),
        migrations.CreateModel(
            name='ParametroLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=3, help_text='Si aplica porcentaje. Ej: 7 para 7%', max_digits=5, null=True)),
                ('valor_moneda', models.DecimalField(blank=True, decimal_places=2, help_text='Si aplica valor fijo o UF', max_digits=12, null=True)),
                ('vigente_desde', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Parámetros Legales (Verificar)',
            },
        ),
        migrations.CreateModel(
            name='TablaImpuestoUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.DateField(help_text='Primer día del mes (ej. 01/08/2026)')),
                ('valor_utm', models.DecimalField(decimal_places=2, help_text='Valor UTM vigente (verificar en sii.cl antes del cierre)', max_digits=10)),
                ('tramo_desde_utm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tramo_hasta_utm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('factor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('rebaja', models.DecimalField(decimal_places=2, help_text='Monto de rebaja en pesos', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('rut', models.CharField(help_text='Formato: 12345678-K', max_length=12, unique=True, validators=[rrhh.models.validate_rut])),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Plazo Fijo', 'Plazo Fijo'), ('Por Obra/Faena', 'Por Obra/Faena')], max_length=50, verbose_name='Tipo de Contrato')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('unidad_negocio', models.CharField(max_length=150, verbose_name='Unidad de Negocio')),
                ('sueldo_base', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Sueldo Base ($)')),
                ('sistema_salud', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre')], max_length=50, verbose_name='Sistema de Salud')),
                ('isapre_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Isapre')),
                ('isapre_plan_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Plan Isapre (UF)')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta Bancaria')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.afp', verbose_name='AFP')),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('sueldo_base', models.DecimalField(decimal_places=0, max_digits=12)),
                ('gratificacion_legal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('horas_extra_monto', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-anio', '-mes', 'empleado__nombre_completo'],
                'unique_together': {('empleado', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='HaberAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('imponible', models.BooleanField(default=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haberes', to='rrhh.liquidacionsueldo')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='rrhh.liquidacionsueldo')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('Presente', 'Presente'), ('Falta Justificada', 'Falta Justificada'), ('Falta Injustificada', 'Falta Injustificada'), ('Licencia Médica', 'Licencia Médica'), ('Vacaciones', 'Vacaciones'), ('Feriado', 'Feriado')], default='Presente', max_length=50)),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('horas_extra', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
