# Generated by Django 6.0.2 on 2026-07-10 00:44

import datetime
from django.db import migrations


def load_initial_data(apps, schema_editor):
    AFP = apps.get_model('rrhh', 'AFP')
    ParametroLegal = apps.get_model('rrhh', 'ParametroLegal')
    TablaImpuestoUnico = apps.get_model('rrhh', 'TablaImpuestoUnico')
    
    # AFPs vigentes
    afps = [
        ("Capital", "1.44"),
        ("Cuprum", "1.44"),
        ("Habitat", "1.27"),
        ("Modelo", "0.58"),
        ("PlanVital", "1.16"),
        ("ProVida", "1.45"),
        ("Uno", "0.69"),
    ]
    for nombre, comision in afps:
        AFP.objects.create(nombre=nombre, comision_porcentaje=comision)
        
    # Parametros Legales
    ParametroLegal.objects.create(
        nombre="Tope Imponible AFP (UF)", valor_moneda="84.3"
    )
    ParametroLegal.objects.create(
        nombre="Tope Imponible AFC (UF)", valor_moneda="126.6"
    )
    
    # Tabla Impuesto Único (Tramos fijos UTM) - Valores aproximados UTM que el usuario debe ajustar
    tramos = [
        (0.00, 13.50, 0.000, 0.00),
        (13.50, 30.00, 0.040, 35500.00), # Rebaja demo
        (30.00, 50.00, 0.080, 114000.00),
        (50.00, 70.00, 0.135, 295000.00),
        (70.00, 90.00, 0.230, 732000.00),
        (90.00, 120.00, 0.304, 1170000.00),
        (120.00, 310.00, 0.350, 1530000.00),
        (310.00, None, 0.400, 2550000.00),
    ]
    
    hoy = datetime.date.today()
    primer_dia_mes = datetime.date(hoy.year, month=hoy.month, day=1) if hasattr(hoy, 'month') else datetime.date.today().replace(day=1)
    
    for desde, hasta, factor, rebaja in tramos:
        TablaImpuestoUnico.objects.create(
            mes_vigencia=primer_dia_mes,
            valor_utm="65000.00", # Valor UTM referencial
            tramo_desde_utm=desde,
            tramo_hasta_utm=hasta,
            factor=factor,
            rebaja=rebaja
        )

class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
